spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"